# Introduction

```{r setup, include=FALSE}
source("knitr-options.R")
source("spelling-check.R")
```

## Prerequisites

- Have at least a basic knowledge of R,

- Install recent versions of [R](https://www.r-project.org/) (>= 3.4) and [RStudio](https://www.rstudio.com/products/rstudio/download/#download) (>= 1.2),

- Install associated package **advr38pkg** with `remotes::install_github("privefl/advr38pkg")`; this will install other dependencies that are needed in this book.

- Install Git and create a GitHub account

## Content

It is impossible to become expert in R in only one training course. Yet, this course aims at giving a wide understanding of many aspects of R. Some external resources will be referred to in this book for you to be able to deepen what you would have learned in this course.

This course was originally composed of 9 sessions (3 hours each):

1. R programming and good practices (1.5 sessions)
2. Data analysis with the tidyverse (3.5 sessions)
3. R code performance (2 sessions)
4. R packages (1 session)
5. Bonus: Shiny (1 session)

## Useful resources

- [Course on R debugging and robust programming](https://github.com/lgatto/2016-02-25-adv-programming-EMBL) by Laurent Gatto & Robert Stojnic,

- [Data Challenge Lab](https://dcl-2017-04.github.io/curriculum/upcoming.html) by Hadley Wickham,

- [Advanced R](http://adv-r.had.co.nz/) by Hadley Wickham, and [some solutions](https://bookdown.org/Tazinho/Advanced-R-Solutions/),

- [R for Data Science](http://r4ds.had.co.nz/index.html) by Garrett Grolemund & Hadley Wickham, and [some solutions](https://jrnold.github.io/r4ds-exercise-solutions/),

- [R packages](http://r-pkgs.had.co.nz/) by Hadley Wickham,

- [Efficient R programming](https://bookdown.org/csgillespie/efficientR/) by Colin Gillespie & Robin Lovelace,

- [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/) by Roger D. Peng,

- [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/) by Roger D. Peng, Sean Kross and Brooke Anderson,

- other resources linked from these materials.


