# R programming

```{r, include=FALSE}
source("knitr-options.R")
source("spelling-check.R")
```

## Useful R base

In this section, I mention some useful R base functions (also see [this comprehensive list in French](https://cran.r-project.org/doc/contrib/Kauffmann_aide_memoire_R.pdf) and [this one](https://github.com/peterhurford/adv-r-book-solutions/blob/master/03_vocab/functions.r)):

### General

```{r}
# To get some help
?topic

# Run code from the example section
example(sum)
```

```{r}
# Structure overview
str(iris)

# List objects of environment
a <- 1:4; b <- list()
ls()

# Remove objects from the environment
rm(list = ls())  ## remove everything
```

```{r}
# list of available S3 methods
methods(summary)
methods(class = "lm")
```

### Sequence and vector operations

```{r}
1:10  ## integers
seq(1, 10, by = 2)
seq(1, 100, length.out = 10)
seq_len(5)
seq_along(5:8)
rep(1:4, 2)
rep(1:4, each = 2)
rep(1:4, 4:1)
rep_len(1:3, 7)
replicate(5, rnorm(10))
```

```{r}
sort(c(1, 6, 8, 2, 2))
order(c(1, 6, 8, 2, 2), c(0, 0, 0, 2, 1))
sort(c("a1", "a2", "a10"))
gtools::mixedsort(c("a1", "a2", "a10"))  # not in base, obviously
which.max(c(1, 5, 3, 6, 2, 0))
which.min(c(1, 5, 3, 6, 2, 0))
unique(c(1, NA, 2, 3, 2, NA, 3))
table(rep(1:4, 4:1))
table(A = c(1, 1, 1, 2, 2), B = c(1, 2, 1, 2, 1))
```

```{r}
round(x <- runif(10, max = 100))
round(x, digits = 2)
round(x, -1)
pmin(1:4, 4:1)
pmax(1:4, 4:1)
outer(1:4, 1:3, '+')
expand.grid(param1 = c(5, 50), param2 = c(1, 3, 10))
```


### Character operations

```{r}
paste("I", "am", "me")
paste0("test", 0)
paste0("PC", 1:10)
me <- "Florian"
glue::glue("I am {me}")  ## not in base, but SO useful
(x <- list.files(pattern = "\\.Rmd$"))
sub("\\.Rmd$", ".pdf", x)
(y <- sample(letters[1:4], 10, replace = TRUE))
match(y, letters[1:4])
y %in% letters[1:2]
rle(rep(1:4, 4:1))
split(1:12, rep(letters[1:3], 4))
intersect(letters[1:4], letters[3:5])
union(letters[1:4], letters[3:5])
setdiff(letters[1:4], letters[3:5])
```

### Logical operators

```{r}
tryCatch(TRUE | stop("will go there"), error = function(e) print(e))
TRUE || stop("won't go there")
c(TRUE, FALSE, TRUE, TRUE) & c(FALSE, TRUE, TRUE, TRUE) 
c(TRUE, FALSE, TRUE, TRUE) && c(FALSE, TRUE, TRUE, TRUE)  ## no warning!!
```

```{r}
(x <- rnorm(10))
ifelse(x > 0, x, -x)
```

Beware with `ifelse()` (learn more [there](https://privefl.github.io/blog/On-the-ifelse-function/)), for example 

```{r}
ifelse(FALSE, 0, 1:5)
`if`(FALSE, 0, 1:5)
```

### Exercises

TODO

